# Generated by Django 4.2.19 on 2025-03-09 13:55

import bnk_web.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='documents',
            field=models.FileField(storage=bnk_web.custom_storage.LoanDocumentStorage(), upload_to=''),
        ),
    ]
