# Generated by Django 5.1.6 on 2025-03-10 10:43

import bnk_web.payout_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_loanapplication_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='payout_documents/'),
        ),
        migrations.AlterField(
            model_name='payoutrequest',
            name='application_screenshot',
            field=models.ImageField(storage=bnk_web.payout_storage.PayoutScreenshotStorage(), upload_to=''),
        ),
    ]
